language: python

python:
    - "3.7"
    
before_install:
- export C2X_DIR=$TRAVIS_BUILD_DIR/c2x_2.30
- export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$C2X_DIR
- echo $TRAVIS_BUILD_DIR
- curl -o c2x.tar.gz https://www.c2x.org.uk/c2x_2.30.tgz && tar xf c2x.tar.gz
- ls -al $C2X_DIR
# compile spglib with aclocal/autotools according to c2x instructions
- curl -o spglib.zip https://codeload.github.com/atztogo/spglib/zip/master && unzip spglib.zip
- cd spglib-master/src
- cp $C2X_DIR/Makefile.spglib Makefile
- CFLAGS="-lm -fPIC -shared" make
# compile c2x as shared lib
- cp spglib.h $C2X_DIR
- cp libsymspg.a $C2X_DIR
- cd $C2X_DIR 
- cp $TRAVIS_BUILD_DIR/Makefile.c2x Makefile
- make shared

install:
    - cd $TRAVIS_BUILD_DIR
    - pip install cython --install-option="--no-cython-compile"
    - pip install -r requirements.txt
    - ln -s c2x2py/c2x.pxd .
    - pip install -e .

script:
    - cd c2x2py && py.test
